server {
    # default_server : ce vhost capture TOUS les Host (domaine, IP brute du nœud, ...)
    # et empêche un autre bloc "server" de renvoyer un 403 pour les requêtes par IP
    listen 80 default_server;
    # Accepte le nom de domaine (avec/sans www) ET l'adresse IP brute
    server_name www.my-wordpress.ch my-wordpress.ch 192.168.88.135;

    root /var/www/html;
    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass wordpress:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
}
